Don't throw an exception if API's JSON response lacks an expected key (#273)
Instead of throwing an exception, be more defensive in the code: if
the API's JSON response lacks a key and we correspondingly set a
variable to `None`, then don't call `get()` on the variable, but test
the variable first.

    AttributeError: 'NoneType' object has no attribute 'get'

Fixes #272.